### ISSUE TITLE
배열순서 변경

### ISSUE THREAD

**Issue by joohyuck** [open-transit/campus.ourbus.kr#8]
1. 수요조사 참여하기
2. 현황보기
3. 댓글달기
4. 진행과정 (메인 헤더부분에 버튼으로 스크롤 링크)
5. 눈뜨면도착은?

**Comment by thechunsik** [comment]
댓글달기가 시각적으론 맨 하단에 들어가는게 안어색하긴 한데, 그러면 현황보기랑 댓글달기를 한row에 2:1 비율로 넣어주는건 어떨까?

**Comment by joohyuck** [comment]
@thechunsik  대부분 접속자가 모바일 인걸 고려하면 모바일에선 어렵지 않을까요??

**Comment by thechunsik** [comment]
모바일에선 당연히 width 100%로 잡아야지~

**Comment by thechunsik** [comment]
closed 보고 확인해보니 저상태가 낫겠다, 그리고 클로즈 하기전에 어떻게 마무리지었는지 코멘트 다는거 부탁해~

**Comment by joohyuck** [comment]
@thechunsik  댓글하고 수요조사 결과 2단배치 말하는거죠???
그렇게 하니 데스크탑에서도 조금 산만해지더라구요, 디스커스가 뭔가 요소들이 너무 많아서..??

위에 구조대로 재배열!

**Comment by thechunsik** [comment]
오키 지금 상태가.좋은거같아 :+1: 이슈 클로즈 할 땐 closed and comment 버튼 이용해줘!ㅋㅋ

Outlook에서 보냄




On Mon, Jun 15, 2015 at 12:53 AM -0700, "joohyuck" <notifications@github.com> wrote:












@thechunsik  댓글하고 수요조사 결과 2단배치 말하는거죠???

그렇게 하니 데스크탑에서도 조금 산만해지더라구요, 디스커스가 뭔가 요소들이 너무 많아서..??



위에 구조대로 재배열!
